import math

from core.algorithms import resample_by_distance, trapezoidal_speeds
from utils.converters import convert_units, heading_deg, inches_to_unit, signed_turn

UNIT_NAMES = {"in": "inches", "mm": "mm", "cm": "cm", "m": "m"}
UNIT_CONST = {"in": "INCHES", "mm": "MM", "cm": "CM", "m": "MM"}

DEFAULT_OBJ_NAMES = {
    "LemLib (PROS C++) - moveToPoint/Pose": "chassis",
    "LemLib Path File (.txt, pure pursuit)": "chassis",
    "VEXcode V5 C++ (turn + drive)": "Drivetrain",
    "VEXcode V5 Python (turn + drive)": "drivetrain",
}

TARGET_NAMES = list(DEFAULT_OBJ_NAMES.keys())


def local_frame_components(dx, dy, heading_deg_val):
    h = math.radians(heading_deg_val)
    return (
        dx * math.sin(h) + dy * math.cos(h),
        dx * math.cos(h) - dy * math.sin(h)
    )


def compute_holonomic_wheel_degrees(waypoints_unit, start_heading, wheel_dia_in, gear_ratio, unit):
    circumference = max(math.pi * inches_to_unit(wheel_dia_in, unit), 1e-6)
    ratio = gear_ratio or 1.0
    segs = []

    for i in range(1, len(waypoints_unit)):
        dx, dy = waypoints_unit[i][0] - waypoints_unit[i - 1][0], waypoints_unit[i][1] - waypoints_unit[i - 1][1]
        fwd, right = local_frame_components(dx, dy, start_heading)

        fl = (fwd + right) / circumference * 360.0 * ratio
        fr = (fwd - right) / circumference * 360.0 * ratio
        segs.append((fl, fr, fr, fl))

    return segs


def generate_code(target_name, waypoints_m, smooth_m, settings, pp_spacing):
    """Dispatch to the right generator based on the selected export target."""
    dtype = settings.get("drivetrain_type", "tank_standard")

    if target_name == "LemLib (PROS C++) - moveToPoint/Pose":
        return _gen_lemlib_cpp(waypoints_m, settings)
    elif target_name == "LemLib Path File (.txt, pure pursuit)":
        return _gen_lemlib_path_file(resample_by_distance(smooth_m, pp_spacing), settings)
    elif target_name == "VEXcode V5 C++ (turn + drive)":
        return {
            "holonomic": genv5pyholonomicstd,
            "tank_smart": FORTALEZA_cpp_tank_smart,
        }.get(dtype, FORTALEZA_cpp_tank_standard)(waypoints_m, settings)
    elif target_name == "VEXcode V5 Python (turn + drive)":
        return {
            "holonomic": _gen_vexcode_python_holonomic,
            "tank_smart": FORTALEZA_python_tank_smart,
        }.get(dtype, FORTALEZA_python_tank_standard)(waypoints_m, settings)
    return ""


def target_ext(target_name):
    return "txt" if "Path File" in target_name else ("py" if "Python" in target_name else "cpp")


def target_uses_smooth_source(target_name):
    return target_name == "LemLib Path File (.txt, pure pursuit)"


def _gen_lemlib_cpp(waypoints_m, settings):
    obj = settings["obj_name"] or "chassis"
    pts = convert_units(waypoints_m, settings["units"])
    lines = [
        "// Generated by VEX Path Planner - LemLib (PROS C++)",
        f"// Units: {settings['units']}  |  Track width: {settings['track_width']} in  |  Wheel diameter: {settings['wheel_dia']} in",
        "// NOTE: param names follow LemLib's Params structs - adjust if yours differ"
    ]
    if settings.get("drivetrain_type") == "holonomic":
        lines.append("// WARNING: LemLib only supports tank drivetrains - this code assumes tank")

    lines.extend(["\nvoid autonomous() {", f"    {obj}.setPose({pts[0][0]:.2f}, {pts[0][1]:.2f}, {settings['start_heading']:.1f});" if pts else f"    {obj}.setPose(0, 0, {settings['start_heading']:.1f});"])

    for i, (x, y) in enumerate(pts):
        if i == len(pts) - 1 and len(pts) > 1:
            hdg = heading_deg(x - pts[i - 1][0], y - pts[i - 1][1])
            lines.append(f"    {obj}.moveToPose({x:.2f}, {y:.2f}, {hdg:.1f}, {settings['timeout']}, {{.maxSpeed = {settings['max_speed']}}});")
        elif i > 0:
            lines.append(f"    {obj}.moveToPoint({x:.2f}, {y:.2f}, {settings['timeout']}, {{.maxSpeed = {settings['max_speed']}}});")

    lines.extend([f"    {obj}.waitUntilDone();", "}"])
    return "\n".join(lines)


def _gen_lemlib_path_file(smooth_points_m, settings):
    pts = convert_units(smooth_points_m, settings["units"])
    speeds = trapezoidal_speeds(len(pts), settings["max_speed"])
    lines = [
        "# Generated by VEX Path Planner - LemLib pure-pursuit path asset",
        f"# Units: {settings['units']}  |  Save this as e.g. static/paths/myPath.txt"
    ]
    lines.extend(f"{x:.3f}, {y:.3f}, {speed}" for (x, y), speed in zip(pts, speeds))
    lines.append("endData")
    return "\n".join(lines)


def FORTALEZA_tank_code(waypoints_m, settings, lang="cpp"):
    is_py = (lang == "python")
    obj = settings["obj_name"] or ("drivetrain" if is_py else "Drivetrain")
    pts = convert_units(waypoints_m, settings["units"])
    smart = settings.get("drivetrain_type") == "tank_smart"
    
    unit_str = UNIT_CONST[settings["units"]] if is_py else UNIT_NAMES[settings["units"]]
    
    lines = [
        f"# Generated by VEX Path Planner - VEXcode V5 {'Python' if is_py else 'C++'} (Tank/Differential, {'SmartDrive' if smart else 'no sensor'})",
        "def autonomous():" if is_py else "void autonomous(void) {",
    ]

    heading = settings["start_heading"]
    if smart:
        lines.append(f"    {obj}.{('set_heading' if is_py else 'setHeading')}({heading:.1f}, {('DEGREES' if is_py else 'degrees')});")

    for i in range(1, len(pts)):
        dx, dy = pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]
        d = math.hypot(dx, dy)
        target_hdg = heading_deg(dx, dy)

        if smart:
            turn_cmd = f"{obj}.{'turn_to_heading' if is_py else 'turnToHeading'}({target_hdg:.1f}, {('DEGREES' if is_py else 'degrees')});"
            lines.append(f"    {turn_cmd}")
        else:
            direction, turn_amt = signed_turn(heading, target_hdg)
            if turn_amt > 0.05:
                turn_func = "turn_for" if is_py else "turnFor"
                dir_val = direction if is_py else direction.lower()
                unit_val = "DEGREES" if is_py else "degrees"
                lines.append(f"    {obj}.{turn_func}({dir_val}, {turn_amt:.1f}, {unit_val});")
            heading = target_hdg

        drive_func = "drive_for" if is_py else "driveFor"
        drive_dir = "FORWARD" if is_py else "forward"
        lines.append(f"    {obj}.{drive_func}({drive_dir}, {d:.2f}, {unit_str});")

    if not is_py:
        lines.append("}")
    return "\n".join(lines)


def FORTALEZA_cpp_tank_standard(waypoints_m, settings):
    return FORTALEZA_tank_code(waypoints_m, settings, lang="cpp")


def FORTALEZA_cpp_tank_smart(waypoints_m, settings):
    return FORTALEZA_tank_code(waypoints_m, settings, lang="cpp")


def FORTALEZA_python_tank_standard(waypoints_m, settings):
    return FORTALEZA_tank_code(waypoints_m, settings, lang="python")


def FORTALEZA_python_tank_smart(waypoints_m, settings):
    return FORTALEZA_tank_code(waypoints_m, settings, lang="python")


def _gen_holonomic_code(waypoints_m, settings, lang="cpp"):
    is_py = (lang == "python")
    pts = convert_units(waypoints_m, settings["units"])
    prefix = "" if is_py else "_"
    motor_default = f"{prefix}motor_" if is_py else "Motor"
    
    motors = {
        "fl": settings.get("motor_fl") or f"{motor_default}fl",
        "fr": settings.get("motor_fr") or f"{motor_default}fr",
        "bl": settings.get("motor_bl") or f"{motor_default}bl",
        "br": settings.get("motor_br") or f"{motor_default}br",
    }
    gear_ratio = settings.get("gear_ratio") or 1.0
    segs = compute_holonomic_wheel_degrees(pts, settings["start_heading"], settings["wheel_dia"], gear_ratio, settings["units"])

    lines = [
        f"# Generated by VEX Path Planner - VEXcode V5 {'Python' if is_py else 'C++'} (Holonomic)",
        "def autonomous():" if is_py else "void autonomous(void) {"
    ]

    for leg_num, leg_vals in enumerate(segs, start=1):
        lines.append(f"    # Leg {leg_num}")
        for (m_key, m_name), deg in zip(motors.items(), leg_vals):
            direction = ("FORWARD" if is_py else "forward") if deg >= 0 else ("REVERSE" if is_py else "reverse")
            if is_py:
                lines.append(f"    {m_name}.spin_for({direction}, {abs(deg):.1f}, DEGREES, wait=False)")
            else:
                lines.append(f"    {m_name}.spinFor({direction}, {abs(deg):.1f}, degrees, false);")

        if is_py:
            conds = " or ".join([f"{m}.is_spinning()" for m in motors.values()])
            lines.extend([f"    while {conds}:", "        wait(10, MSEC)"])
        else:
            conds = " || ".join([f"{m}.isSpinning()" for m in motors.values()])
            lines.append(f"    while ({conds}) {{ wait(10, msec); }}")

    if not is_py:
        lines.append("}")
    return "\n".join(lines)


def genv5pyholonomicstd(waypoints_m, settings):
    return _gen_holonomic_code(waypoints_m, settings, lang="cpp")


def _gen_vexcode_python_holonomic(waypoints_m, settings):
    return _gen_holonomic_code(waypoints_m, settings, lang="python")